"""empty message

Revision ID: a5b4b61f765d
Revises: 528ca1ad05bd
Create Date: 2024-04-21 18:08:43.731652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b4b61f765d'
down_revision = '528ca1ad05bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'publication', ['publication_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('publication_id')

    # ### end Alembic commands ###
